import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { HighlightInit } from '@highlight-run/next/client'

import { env } from 'env'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'FWR Internal',
  description: 'Generated by create next app',
}

type IProps = {
  children: React.ReactNode
}
export default function(props: IProps) {
  return (
    <>
      <HighlightInit 
        projectId={env.NEXT_PUBLIC_HIGHLIGHT_ID}
        serviceName='fwr-internal'
        tracingOrigins
        networkRecording={{
          enabled: true,
          recordHeadersAndBody: true,
          urlBlocklist: [],
        }}
      />
      <html lang="en">
        <body className={`dark ${inter.className} bg-gray-950 bg-none h-screen w-screen`}>
          {props.children}
        </body>
      </html>
    </>
  )
}
