version: "3"

services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  nats-js:
    image: nats:2.10.11
    command: -js
    ports:
      - 4222:4222 # client connections
      - 6222:6222 # leaf nodes
      - 8222:8222 # monitoring
