import './index.css'

import Link from 'next/link'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
      <head>
        <title>Feuerwehr Rödingen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <main>
          <div className='main'>
            <nav>
              <Link href='/'>
                Home
              </Link>
              <Link href='/settings'>
                settings
              </Link>
              <Link href='/server'>
                Server
              </Link>
              <Link href='/pocket'>
                pocket
              </Link>
            </nav>
            <div className='mainPage'>
              {children}
            </div> 
          </div>
        </main>
      </body>
    </html>
  )
}
