app: fw-roedingen
org: thomasd01
frameworkVersion: '3'
service: api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  vpc:
    securityGroupIds:
      - sg-03c202ea633717c31
    subnetIds:
      - subnet-059b25101065b207a
      - subnet-0273ddbe93d37bc83S

functions:
  apiGateway:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-esbuild
  - serverless-plugin-monorepo
  - serverless-offline

custom:
  esbuild:
    banner:
      js: import { createRequire } from 'module';const require = createRequire(import.meta.url); 
    bundle: true
    external:
      - amqp-connection-manager
      - amqplib
      - aws-sdk
      - cache-manager
      - class-transformer
      - class-validator
      - kafkajs
      - ioredis
      - mqtt
      - nats
      - stream
      - '@nestjs/websockets/socket-module'
    format: "esm"
    minify: false
    outputFileExtension: ".mjs"
    packager: npm
    platform: "node"
    plugins: plugin.cjs
    sourcemap: true
    target: "esnext"
    watch:
      pattern: ['./index.ts', 'src/**/*.ts']
      ignore: ['.serverless/**/*', '.build']
