name: CI/CD

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: build
        run: cd apps/api && npm ci

      - name: Run a multi-line script
        run: npm run deploy
