name: CI/CD Api

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: check for ignored build step
        run: |
          npx turbo-ignore --filter=fw-roedingen-backend
          if [ $? -eq 0 ]; then
            exit 0
          fi
          echo ignoring build step because api Repo is not affected

      - name: build
        run: cd apps/api && npm install

      - name: deploy to firebase
        run: cd apps/api && npm run deploy
