name: CI/CD Api

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: tasks
        run: |
          sudo npm install -g turbo-ignore
          npx turbo-ignore --filter=fw-roedingen-backend || { 
            echo installing firebase build tools 
            sudo npm install -g firebase-tools

            echo going to api directory
            cd apps/api

            echo installing dependencies
            npm install

            echo deploying everything to firebase
            npx firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}

            exit 0
          }
          exit 0
